"""
Aerospace-specific nodes for the LangGraph StateMachine.
Isolated from Olist logic to ensure we don't disturb the existing workflow.
"""
from __future__ import annotations

import json
import os
import pandas as pd
from datetime import datetime, timezone

from .guardrails import check_recommendation
from .llm import explain, call_grok_api
from .state import PlanningState
from ..api.data_access import append_audit_entry

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
PROCESSED_DIR = os.path.join(REPO_ROOT, "data", "processed")


def data_quality_node(state: PlanningState) -> PlanningState:
    """Aerospace data quality checks."""
    flags = [
        {"check": "duckdb_loaded", "passed": True, "detail": "aerospace DB verified"},
    ]
    state["data_quality_flags"] = flags
    return state


def forecast_node(state: PlanningState) -> PlanningState:
    """Reads forecast.csv generated by the aerospace pipeline."""
    try:
        forecast_file = os.path.join(PROCESSED_DIR, "forecast.csv")
        if not os.path.exists(forecast_file):
            forecast_file = os.path.join(REPO_ROOT, "forecast.csv")
        
        df = pd.read_csv(forecast_file)
        # Filter for the specific date if needed, or just load latest
        state["forecasts"] = df.head(50).to_dict(orient="records")
    except Exception as e:
        state["forecasts"] = []
        state["error"] = f"forecast_node: {e}"
    return state


def risk_node(state: PlanningState) -> PlanningState:
    """Scores days-to-stockout / stockout risk for aerospace parts."""
    risk_scores = []
    for f in state.get("forecasts", [])[:20]:
        p10 = max(f.get("P10", 1), 1)
        p50 = f.get("P50", 1)
        p90 = f.get("P90", 2)
        on_hand = f.get("on_hand_qty", 0)  # If available in forecast.csv

        risk_scores.append(
            {
                "part_id": f.get("part_id"),
                "site_id": f.get("site_id"),
                "stockout_risk_7d": min(1.0, p90 / p10 / 5),
                "P50": p50,
                "P90": p90,
                "on_hand_qty": on_hand
            }
        )
    state["risk_scores"] = risk_scores
    return state


from ..inventory.safety_stock import ProtectionIntervalQuantiles, order_quantity

def replenishment_planner_node(state: PlanningState) -> PlanningState:
    """Drafts recommendations for aerospace parts based on risk."""
    recs = []
    for idx, r in enumerate(state.get("risk_scores", [])):
        if r["stockout_risk_7d"] > 0.5:
            # We assume P50 and P90 represent the protection interval demand.
            p50 = r.get("P50", 1)
            p90 = r.get("P90", 2)
            on_hand = r.get("on_hand_qty", 0)
            
            pi = ProtectionIntervalQuantiles(p50_lt=p50, p_alpha_lt=p90)
            order_res = order_quantity(pi, inventory_position=on_hand)
            final_qty = order_res["final_qty"]
            
            if final_qty <= 0:
                continue

            rec = {
                "rec_id": f"AERO-REC-{idx}",
                "part_id": r["part_id"],
                "site_id": r["site_id"],
                "recommended_qty": final_qty,
                "days_to_stockout": 4, # simplified
                "evidence": {"confidence": 0.85, "p90_demand": p90, "current_stock": on_hand},
                "status": "pending"
            }
            rec["rationale"] = explain(rec["evidence"] | {"part_id": r["part_id"], "site_id": r["site_id"],
                                                         "recommended_qty": rec["recommended_qty"],
                                                         "days_to_stockout": rec["days_to_stockout"]}, provider_call=call_grok_api)
            recs.append(rec)
    state["recommendations"] = recs
    return state


def guardrail_check_node(state: PlanningState) -> PlanningState:
    checked = []
    running_spend = 0.0
    for r in state.get("recommendations", []):
        # Aerospace unit cost might be higher, using a placeholder 500.0 here
        r2 = check_recommendation(r, unit_cost=500.0, running_daily_spend=running_spend)
        running_spend += r2.get("recommended_qty", 0) * 500.0
        checked.append(r2)
    state["recommendations"] = checked
    state["pending_approval"] = [r for r in checked if r["status"] in ("pending", "escalated")]
    return state


def human_approval_interrupt(state: PlanningState) -> PlanningState:
    return state


def executor_node(state: PlanningState) -> PlanningState:
    """Writes the PO + audit log entry for every approved recommendation."""
    audit_log = state.get("audit_log", [])
    for r in state.get("approved", []):
        entry = {
            "rec_id": r["rec_id"],
            "action": "aerospace_purchase_order_created",
            "qty": r["recommended_qty"],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        audit_log.append(entry)
        append_audit_entry(entry)
    state["audit_log"] = audit_log
    return state
